title: D3Capital
author: ""
description: Systematic Investor · Capital Research · Data-Driven Arbitrage
theme: minima
timezone: Asia/Shanghai
future: true

plugins:
  - jekyll-feed

header_pages:
  - index.md
  - research.md
  - journal.md
  - views.md
navigation:
  - title: Research
    url: /research
  - title: About
    url: /about
