title: D3Capital
description: Systematic Investor · Capital Research · Data-Driven Arbitrage
theme: minima
future: true
timezone: Asia/Shanghai

plugins:
  - jekyll-feed

header_pages:
  - research.md
  - journal.md
  - views.md
