title: D3Capital
author: ""
description: Systematic Investor · Capital Research · Data-Driven Arbitrage
theme: minima
timezone: Asia/Shanghai
future: true

plugins:
  - jekyll-feed

header_pages:
  - index.md
  - research.md
  - journal.md
  - views.md
collections:
  research:
    output: true
    permalink: /research/:name/
  journal:
    output: true
    permalink: /journal/:name/
  views:
    output: true
    permalink: /views/:name/
